apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: clone-repo-run
spec:
  pipelineRef:
    name: clone-repo-pipeline
  params:
    - name: repo-url
      value: https://github.com/ayubazmi/Ruby-Rail-Private.git
    - name: revision
      value: main
  workspaces:
    - name: shared-data
      persistentVolumeClaim:
        claimName: shared-data-pvc

