version: 2.1

parameters:
  build_tag:
    type: string
    default: ""

jobs:
  checkout-code:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - checkout

  build-and-push:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build & Tag Images
          command: |
            TAG=${CIRCLE_PIPELINE_ID:0:8}
            docker build -t my-postgres-db -f Dockerfile.db .
            docker tag my-postgres-db $DOCKERHUB_USERNAME/my-postgres-db:$TAG

            docker build -t my-rails-app -f Dockerfile.app .
            docker tag my-rails-app $DOCKERHUB_USERNAME/my-rails-app:$TAG
      - run:
          name: Push Images
          command: |
            TAG=${CIRCLE_PIPELINE_ID:0:8}
            docker push $DOCKERHUB_USERNAME/my-postgres-db:$TAG
            docker push $DOCKERHUB_USERNAME/my-rails-app:$TAG

  update-k8s-yaml:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Clone & Update Kubernetes YAMLs
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git clone https://$GITHUB_TOKEN@github.com/ayubazmi/CircleCi.git updated-yamls
            cd updated-yamls

            TAG=${CIRCLE_PIPELINE_ID:0:8}
            sed -i "s|\(image: $DOCKERHUB_USERNAME/my-rails-app:\).*|\1$TAG|" k8s/rails-deployment.yaml
            sed -i "s|\(image: $DOCKERHUB_USERNAME/my-postgres-db:\).*|\1$TAG|" k8s/postgres-deployment.yaml

            git add k8s/*.yaml
            git commit -m "Update image tags to build $TAG [ci skip]"
            git push origin main
#gta
workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout-code
      - build-and-push:
          requires:
            - checkout-code
      - update-k8s-yaml:
          requires:
            - build-and-push
