version: 2.1

jobs:
  checkout-code:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - checkout

  build-and-push:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Login to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Build & Tag Images
          command: |
            docker build -t my-postgres-db -f Dockerfile.db .
            docker tag my-postgres-db $DOCKERHUB_USERNAME/my-postgres-db:${CIRCLE_BUILD_NUM}

            docker build -t my-rails-app -f Dockerfile.app .
            docker tag my-rails-app $DOCKERHUB_USERNAME/my-rails-app:${CIRCLE_BUILD_NUM}

      - run:
          name: Push Images
          command: |
            docker push $DOCKERHUB_USERNAME/my-postgres-db:${CIRCLE_BUILD_NUM}
            docker push $DOCKERHUB_USERNAME/my-rails-app:${CIRCLE_BUILD_NUM}

  update-k8s-yaml:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Clone & Update Kubernetes YAMLs
          command: |
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git clone https://$GITHUB_TOKEN@github.com/ayubazmi/Ruby-Rail-Private.git updated-yamls
            cd updated-yamls

            sed -i "s|\(image: $DOCKERHUB_USERNAME/my-rails-app:\).*|\1${CIRCLE_BUILD_NUM}|" k8s/rails-deployment.yaml
            sed -i "s|\(image: $DOCKERHUB_USERNAME/my-postgres-db:\).*|\1${CIRCLE_BUILD_NUM}|" k8s/postgres-deployment.yaml

            git add k8s/*.yaml
            git commit -m "Update image tags to build ${CIRCLE_BUILD_NUM} [skip ci]"
            git push origin main

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout-code
      - build-and-push:
          requires:
            - checkout-code
      - update-k8s-yaml:
          requires:
            - build-and-push
