version: 2.1

jobs:
  checkout-code:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Generate consistent build tag
          command: |
            echo "export BUILD_TAG=${CIRCLE_BUILD_NUM}" > build_tag.env
      - persist_to_workspace:
          root: .
          paths:
            - build_tag.env

  build-and-push:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Load build tag
          command: source build_tag.env
      - checkout
      - setup_remote_docker
      - run:
          name: Login to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build & Tag Images
          command: |
            source build_tag.env
            docker build -t my-postgres-db -f Dockerfile.db .
            docker tag my-postgres-db $DOCKERHUB_USERNAME/my-postgres-db:$BUILD_TAG

            docker build -t my-rails-app -f Dockerfile.app .
            docker tag my-rails-app $DOCKERHUB_USERNAME/my-rails-app:$BUILD_TAG
      - run:
          name: Push Images
          command: |
            source build_tag.env
            docker push $DOCKERHUB_USERNAME/my-postgres-db:$BUILD_TAG
            docker push $DOCKERHUB_USERNAME/my-rails-app:$BUILD_TAG

  update-k8s-yaml:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Load build tag
          command: source build_tag.env
      - checkout
      - run:
          name: Clone & Update Kubernetes YAMLs
          command: |
            source build_tag.env
            git config --global user.name "$GIT_USER_NAME"
            git config --global user.email "$GIT_USER_EMAIL"
            git clone https://$GITHUB_TOKEN@github.com/ayubazmi/Ruby-Rail-Private.git updated-yamls
            cd updated-yamls

            sed -i "s|\(image: $DOCKERHUB_USERNAME/my-rails-app:\).*|\1$BUILD_TAG|" k8s/rails-deployment.yaml
            sed -i "s|\(image: $DOCKERHUB_USERNAME/my-postgres-db:\).*|\1$BUILD_TAG|" k8s/postgres-deployment.yaml

            git add k8s/*.yaml
            git commit -m "Update image tags to build $BUILD_TAG [skip ci]"
            git push origin main

workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - checkout-code
      - build-and-push:
          requires:
            - checkout-code
      - update-k8s-yaml:
          requires:
            - build-and-push
