jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build & Tag Images
          command: |
            docker build -t my-postgres-db -f Dockerfile.db .
            docker tag my-postgres-db $DOCKERHUB_USERNAME/my-postgres-db:${CIRCLE_BUILD_NUM}
            docker build -t my-rails-app -f Dockerfile.app .
            docker tag my-rails-app $DOCKERHUB_USERNAME/my-rails-app:${CIRCLE_BUILD_NUM}
      - run:
          name: Push Images
          command: |
            docker push $DOCKERHUB_USERNAME/my-postgres-db:${CIRCLE_BUILD_NUM}
            docker push $DOCKERHUB_USERNAME/my-rails-app:${CIRCLE_BUILD_NUM}
workflows:
  version: 2
  deploy_pipeline:
    jobs:
      - build-and-push
      - update-k8s-yaml:
          requires:
            - build-and-push
      - deploy:
          requires:
            - update-k8s-yaml
